name = "adventure"
main = "_worker.ts"
compatibility_date = "2025-05-16"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "Lobby" }
]

[[migrations]]
tag = "v1"
new_classes = ["Lobby"]
