name = "adventure"
main = "frontend/public/_worker.js"
compatibility_date = "2025-05-16"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./frontend/public"

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "Lobby" }
]

[[migrations]]
tag = "v1"
new_classes = ["Lobby"]

[build]
command = ""
