import type { OneShotCampaign } from '../types';
export const theCursedWedding: OneShotCampaign = {
  id: 'oneshot-cursed-wedding', type: 'oneshot', title: 'The Cursed Wedding', tagline: 'The bride is undead. The groom doesn\'t care. The in-laws want blood.', tone: 'horror', themes: ['horror', 'social'], playerCount: { min: 3, max: 6 }, level: 5, estimatedHours: 4,
  settingSummary: 'The party is invited to a wedding in a remote manor. The bride died three days ago and was raised as intelligent undead by a desperate groom who couldn\'t let go. She\'s fully herself — memories, personality, love — just dead. The groom\'s family is horrified. The bride\'s family doesn\'t know yet. And the necromantic energy holding her together is attracting something from the nearby cemetery.',
  hook: 'The invitation is beautiful. The venue is a gothic manor. The groom greets the party warmly. The bride appears — pale, cold to the touch, and smiling. "I know I look different. I died. He brought me back. We\'re getting married anyway. Please don\'t make this weird."',
  twist: 'The bride isn\'t just undead — she\'s evolving. The necromantic magic is slowly transforming her into something more powerful. By tomorrow, she\'ll be a revenant — strong, immortal, and consumed by a single purpose. Right now her purpose is love. If anything disrupts the wedding, her purpose could shift to revenge. The party must ensure the wedding goes smoothly to lock in "love" as her revenant purpose.',
  climax: 'The cemetery dead rise during the ceremony, drawn by necromantic energy. The in-laws panic. The bride\'s transformation accelerates. The party must protect the ceremony, keep the bride focused on love (not vengeance), and fight off the undead incursion — all while the vows are being spoken.',
  scenes: [
    { title: 'Scene 1: The Rehearsal', summary: 'Arrival, meeting the couple, and the dawning realization that the bride is dead. Social horror as the party navigates this... unusual situation.', challenge: 'social', keyEvents: ['The groom: "Before you judge, let me explain. I loved her. She died. I brought her back. She said yes."', 'The bride: fully herself, slightly cold, sense of humor about her condition — "I don\'t eat much anymore. Silver lining."', 'The in-laws arrive: the groom\'s mother faints, the bride\'s father reaches for his sword', 'The party must manage both families while the bride\'s necromantic aura causes candles to flicker'] },
    { title: 'Scene 2: The Eve', summary: 'The night before the wedding. Strange activity in the cemetery. The bride\'s transformation begins. The party discovers what she\'s becoming.', challenge: 'exploration', keyEvents: ['Cemetery disturbance: the dead are restless — drawn by the bride\'s growing power', 'The bride feels it: "Something is changing. I feel... stronger. Angrier. Is that normal?"', 'Research: a cleric identifies the revenant transformation — purpose locks at the strongest emotion during the transition', 'The plan: the wedding must happen DURING the transformation so "love" becomes the permanent purpose'] },
    { title: 'Scene 3: The Ceremony', summary: 'The wedding. The dead rise. The bride transforms. The vows must be completed before anger replaces love.', challenge: 'combat', keyEvents: ['The ceremony begins: beautiful, gothic, slightly cold (the bride)', 'The dead arrive: shambling up from the cemetery, drawn to the bride', 'The party defends: fighting undead on the church steps while the vows continue inside', 'The transformation: the bride\'s eyes glow — the final vow, spoken with feeling, locks "love" as her purpose'] },
  ],
  keyNPCs: [
    { name: 'Elise (the bride)', role: 'the dead bride / sympathetic', personality: 'A woman who died of a sudden illness and was brought back by love (and necromancy). Funny, kind, and increasingly powerful. "I know this is weird. It\'s weird for me too. But I love him and death didn\'t change that."' },
    { name: 'Thomas (the groom)', role: 'desperate romantic', personality: 'A man who couldn\'t accept losing the love of his life and taught himself enough necromancy to bring her back. Not a villain — just a romantic who went too far. "I know what I did was wrong. I\'d do it again."' },
    { name: 'Father Aldric (officiant)', role: 'reluctant cleric', personality: 'A cleric who agreed to perform the ceremony because "love is love, even when one party is clinically dead." Deeply conflicted. Performing the rite with shaking hands.' },
  ],
  keyLocations: [
    { name: 'Thornwood Manor', description: 'A gothic manor in the countryside. Beautiful in a spooky way. The bride\'s aura makes all the roses bloom black.', significance: 'Where the wedding takes place.' },
    { name: 'The Chapel', description: 'A small stone chapel on the manor grounds. The stained glass depicts love stories. The temperature drops 10 degrees near the altar.', significance: 'Where the ceremony and climax occur.' },
    { name: 'The Cemetery', description: 'An old graveyard adjacent to the chapel. The dead are restless. They can feel the bride\'s power. They\'re coming.', significance: 'The source of the undead threat.' },
  ],
  dataSystems: ['hauntedLocation', 'encounterWaves', 'socialEncounter', 'deathSaveDrama', 'combatNarration', 'darkBargain'],
};
