import type { OneShotCampaign } from '../types';
export const theInvisibleWar: OneShotCampaign = {
  id: 'oneshot-invisible-war', type: 'oneshot', title: 'The Invisible War', tagline: 'Two armies fight a battle nobody can see. You just walked into the middle.', tone: 'serious', themes: ['war', 'mystery'], playerCount: { min: 3, max: 5 }, level: 7, estimatedHours: 4,
  settingSummary: 'The party walks through a quiet meadow. A sword wound appears on the fighter\'s arm from nothing. An arrow thuds into a tree with no archer visible. The ground shakes from impacts nobody can see. Two armies of invisible soldiers are fighting a battle in this field, and the party is standing in no-man\'s land.',
  hook: 'A peaceful field. Birds singing. Then the fighter stumbles — a slash across their arm from nothing. Then an explosion of dirt six feet away with no sound. Then a scream from a voice that isn\'t there. Something is happening here. Something violent. Something invisible.',
  twist: 'The armies aren\'t invisible — they\'re from a different timeline. Two armies that fought a massive battle on this field 500 years ago are bleeding through time. The party is in both timelines simultaneously. When they figure out how to fully shift into the past, they find themselves on the eve of a battle they could prevent.',
  climax: 'The party fully phases into the past. The battle hasn\'t started yet — two generals face each other across the field. The party has one hour before the timeline reasserts itself and sends them home. They can try to prevent the battle (saving thousands), let it happen (preserving the timeline), or change the outcome (rewriting 500 years of history).',
  scenes: [
    { title: 'Scene 1: No-Man\'s Land', summary: 'The invisible violence. The party is hurt by attacks from nowhere. Investigation reveals something temporal.', challenge: 'exploration', keyEvents: ['First wounds: slashes, arrows, and explosions from invisible sources', 'Pattern: the violence follows formation — these are organized troops', 'Temporal residue: a detect magic spell shows the field saturated with time energy', 'A ghost soldier becomes briefly visible: armor from 500 years ago, mid-charge, confused to see the party'] },
    { title: 'Scene 2: The Phasing', summary: 'The party learns to shift perception. Flickering between present and past. In the past, two armies prepare for war.', challenge: 'exploration', keyEvents: ['Phasing: touching certain objects shifts perception — the present becomes ghostly, the past becomes solid', 'The past revealed: two armies camped on opposite sides of the field, banners flying', 'Speaking to soldiers: they\'re scared, young, and don\'t want to fight', 'The generals: two stubborn commanders who could end this with a conversation'] },
    { title: 'Scene 3: The Eve of Battle', summary: 'Fully in the past. One hour before the timeline reasserts. The party can change history — or let it happen.', challenge: 'social', keyEvents: ['Full phase: the party is in the past, visible, and the armies notice them', 'The generals: each has reasons for war — neither has tried talking to the other', 'The intervention: the party can mediate, sabotage, or fight — each changes the timeline', 'The return: the party snaps back to the present — the field is either a battlefield memorial or... something else'] },
  ],
  keyNPCs: [
    { name: 'General Aldric Ironheart', role: 'past commander / one side', personality: 'A general who fights because his king commanded it. He doesn\'t hate his enemy. He doesn\'t want this war. But he will fight because that\'s what soldiers do.' },
    { name: 'General Sera Windcrest', role: 'past commander / other side', personality: 'A general who fights to protect her homeland from invasion. She doesn\'t know Aldric was ordered here against his will. If she did, everything would change.' },
    { name: 'The Field', role: 'environmental / temporal', personality: 'The field itself is the "NPC" — it remembers the battle and replays it. Grass grows red in patches. The wind carries echoes of screams.' },
  ],
  keyLocations: [
    { name: 'The Meadow (Present)', description: 'A peaceful field with wildflowers. Except for the invisible violence and the patches of grass that grow suspiciously red.', significance: 'Where the party starts and where the phasing occurs.' },
    { name: 'The Battlefield (Past)', description: 'The same field, 500 years ago. Two armies, 10,000 soldiers, banners flying, and the dawn of a battle that hasn\'t started yet.', significance: 'Where the choice is made.' },
    { name: 'The Generals\' Tents', description: 'Command tents on opposite sides of the field. Each contains maps, orders, and personal letters that reveal the truth about why this war is being fought.', significance: 'Where the information to prevent the battle is found.' },
  ],
  dataSystems: ['massCombat', 'timeLoopDungeon', 'diplomaticNegotiation', 'socialEncounter', 'warRoomBriefing', 'combatNarration'],
};
