import type { OneShotCampaign } from '../types';
export const theKrakenWakes: OneShotCampaign = {
  id: 'oneshot-kraken-wakes', type: 'oneshot', title: 'The Kraken Wakes', tagline: 'It\'s bigger than the ship. It\'s angry. And it just asked you a riddle.', tone: 'epic', themes: ['nautical', 'epic', 'classic_fantasy'], playerCount: { min: 3, max: 6 }, level: 10, estimatedHours: 4,
  settingSummary: 'The party is on a ship when a kraken surfaces. Not to attack — to talk. It has been trapped in the shallows by a magical net cast by a lich, and it needs mortal hands to cut the invisible chains. In exchange, it will grant a wish. The catch: the lich is nearby, the net is guarded, and the kraken can\'t control its thrashing — every few minutes, a tentacle nearly capsizes the ship.',
  hook: 'The ocean bulges. A tentacle the size of a mast rises from the water. An eye the size of a rowboat opens. A voice that vibrates in their bones: "MORTALS. I REQUIRE... ASSISTANCE. PLEASE." The kraken winces. "THE NET IS TIGHT. EVERY MOVEMENT HURTS. WILL YOU HELP?"',
  twist: 'The kraken didn\'t say whose wish it would grant. The wish goes to the one who cuts the final chain — and the lich\'s servants are also trying to cut the chains, intending to claim the wish for their master. The party must cut the chains AND ensure they\'re the ones who cut the last one.',
  climax: 'Underwater combat around the magical chains. The lich\'s undead servants are cutting from the other side. The kraken thrashes in pain, making the water a hazardous environment. The party must cut the final chain before the lich\'s forces do — and then survive the kraken\'s gratitude (it\'s enthusiastic, it\'s enormous, and it doesn\'t understand "gentle").',
  scenes: [
    { title: 'Scene 1: The Plea', summary: 'The kraken surfaces, explains its situation, and the party must decide to help — while dodging its involuntary tentacle flailing.', challenge: 'social', keyEvents: ['The kraken rises: tentacles, eye, and a voice that makes the ship vibrate', 'The plea: it\'s trapped, it\'s in pain, and it can\'t free itself', 'The deal: cut the chains, get a wish — the kraken is surprisingly polite', 'Involuntary thrashing: the ship is rocked as the kraken struggles against the net'] },
    { title: 'Scene 2: The Chains', summary: 'Diving underwater to find and cut the magical chains holding the kraken. The lich\'s servants are already there.', challenge: 'combat', keyEvents: ['Diving: water-breathing spells or potions, into the deep', 'The net: invisible chains anchored to the sea floor, glowing with necrotic energy', 'The lich\'s forces: undead divers cutting chains from the far side', 'A race: 6 chains total, the party must cut more than the lich\'s team'] },
    { title: 'Scene 3: The Last Chain', summary: 'One chain remains. Both sides converge. The kraken can feel freedom approaching. Underwater combat at the final anchor point.', challenge: 'combat', keyEvents: ['The final chain: both groups reach it simultaneously', 'Underwater battle: the party vs. undead servants of a lich, in the shadow of a kraken', 'The cut: whoever severs the last chain gets the wish', 'The kraken freed: grateful, enthusiastic, and accidentally destructive — "THANK YOU! LET ME HUG YOUR SHIP— wait, too hard, too hard—"'] },
  ],
  keyNPCs: [
    { name: 'The Kraken (Tempest)', role: 'quest giver / environmental hazard', personality: 'An ancient kraken with the vocabulary of a scholar and the enthusiasm of a puppy. Polite, grateful, and absolutely devastating when excited. "I AM SO HAPPY! I WILL SHOW MY GRATITUDE! PLEASE HOLD STILL WHILE I— oh. Your mast. I am... so sorry."' },
    { name: 'The Lich (Nethros)', role: 'antagonist / distant', personality: 'Never seen. His presence is felt through the undead who move with unnatural coordination and the necrotic chains that pulse to a heartbeat only he can hear. His final chain-cutter carries a scroll that reads: "Bring the wish. Do not bring excuses."' },
    { name: 'First Mate Coral', role: 'ship crew / ally', personality: 'The ship\'s first mate who has seen many things but never a polite kraken. Adapting in real time. "I\'ve sailed 30 years. I was NOT briefed on diplomatic krakens."' },
  ],
  keyLocations: [
    { name: 'The Ship (The Wavecrest)', description: 'The party\'s vessel, currently parked next to a kraken. The crew is handling it surprisingly well (they\'re not).', significance: 'The party\'s base of operations.' },
    { name: 'The Undersea Chains', description: '6 magical chains anchored to the sea floor, each glowing with necrotic energy. The kraken is tangled in them.', significance: 'The dungeon — underwater chain-cutting while fighting.' },
    { name: 'The Final Anchor', description: 'The last chain\'s anchor point — a massive necrotic crystal on the ocean floor where both groups converge.', significance: 'The climactic battle location.' },
  ],
  dataSystems: ['navalCombat', 'encounterWaves', 'combatNarration', 'chaseSequence', 'darkBargain', 'treasureGenerator'],
};
