import type { OneShotCampaign } from '../types';
export const thePiratesCourt: OneShotCampaign = {
  id: 'oneshot-pirates-court', type: 'oneshot', title: 'The Pirate\'s Court', tagline: 'A pirate trial. You\'re the jury. The defendant has a cannon.', tone: 'social', themes: ['social', 'nautical', 'comedy'], playerCount: { min: 3, max: 6 }, level: 5, estimatedHours: 4,
  settingSummary: 'The Pirate Code demands a trial when a captain is accused of breaking the Articles. Captain Red Mara stands accused of "being too nice" — returning stolen cargo, apologizing to victims, and once rescuing a naval officer. The party is selected as the jury at the floating pirate court of Freeport. Every juror who\'s ever acquitted has been thrown overboard.',
  hook: 'The party is press-ganged onto a jury ship. A one-eyed judge slams a gavel made from a ship\'s wheel: "Captain Red Mara, you stand accused of Insufficient Piracy. How do you plead?" Mara: "Not guilty. I\'m an EXCELLENT pirate. I just have... ethics."',
  twist: 'Mara has been deliberately acting "nice" to infiltrate the navy\'s trust, positioning herself for the biggest heist in pirate history — stealing the Royal Treasury Ship. Her "kindness" was a long con. She\'s not on trial for being too nice — she\'s on trial because the other captains are jealous and want to stop her before she pulls off the heist alone.',
  climax: 'During closing arguments, Mara reveals the heist plan. The court erupts. Half the pirates want in, half want her hanged for not sharing. The party must deliver a verdict that either condemns Mara (ending the heist), acquits her (letting the heist happen), or declares a mistrial (freeing Mara and starting a pirate civil war).',
  scenes: [
    { title: 'Scene 1: Jury Selection', summary: 'The party is "volunteered" as jurors. Meet the accused, the prosecution, and the colorful pirate spectators.', challenge: 'social', keyEvents: ['Press-ganged: "Congratulations, you\'re jurors. Try to swim if you don\'t like it."', 'Meet Mara: charming, unapologetic, and clearly smarter than everyone in the room', 'The charges read: 12 counts of niceness, including "said please during a boarding"', 'The prosecution: Captain Blacktooth, who just really doesn\'t like Mara'] },
    { title: 'Scene 2: The Trial', summary: 'Witnesses, evidence, and pirate legal arguments. The prosecution presents Mara\'s acts of kindness as crimes. The defense argues... creatively.', challenge: 'social', keyEvents: ['Prosecution witness: a merchant who says Mara returned his cargo with a NOTE APOLOGIZING', 'Defense witness: a sailor who says Mara\'s crew is the most loyal on the sea (because she\'s nice to them)', 'Evidence: Mara\'s ship log, which reads like a diary of a pirate having a moral crisis', 'Jury deliberation: the party can investigate further, interview witnesses, or snoop'] },
    { title: 'Scene 3: The Verdict', summary: 'Mara reveals the long con. The court goes wild. The party must render judgment in the middle of a pirate uproar.', challenge: 'social', keyEvents: ['Mara\'s reveal: "Every act of kindness was a chess move. The Treasury Ship docks in three days."', 'Pirate uproar: some want in, some want her dead, the judge wants ORDER', 'The verdict: guilty (heist dies), not guilty (heist lives), mistrial (chaos)', 'The aftermath: whatever the verdict, Mara winks at the party'] },
  ],
  keyNPCs: [
    { name: 'Captain Red Mara', role: 'defendant / mastermind', personality: 'A pirate captain who is genuinely kind AND a genius strategist. She played nice for three years to set up the perfect heist. "I\'m not nice because I\'m soft. I\'m nice because it\'s the best disguise."' },
    { name: 'Captain Blacktooth', role: 'prosecution / jealous', personality: 'A traditional pirate who considers niceness a disease. Prosecuting Mara because he couldn\'t figure out her plan and assumes she\'s just weak. "A pirate who says PLEASE? DISGRACEFUL."' },
    { name: 'Judge Barnacle', role: 'pirate judge', personality: 'A retired pirate captain who serves as judge. Fair by pirate standards (low bar). His gavel is a wheel. His bench is a ship\'s helm. "ORDER! I said ORDER! The next person who draws a cutlass is in CONTEMPT."' },
  ],
  keyLocations: [
    { name: 'The Court Ship', description: 'A massive galleon converted into a floating courtroom. The witness stand is the crow\'s nest. The jury box is a row of hammocks.', significance: 'Where the trial takes place.' },
    { name: 'Freeport Harbor', description: 'The pirate neutral zone — dozens of ships, a floating market, and an unwritten rule against murder (strongly worded suggestion against it).', significance: 'The wider setting.' },
    { name: 'The Brig', description: 'Where Mara is held between sessions. She\'s somehow acquired a desk, paperwork, and a detailed map of the Treasury Ship route.', significance: 'Where the party can talk to Mara privately.' },
  ],
  dataSystems: ['magicalCourtroom', 'socialEncounter', 'heistPlanner', 'factionReputation', 'navalCombat'],
};
