import type { OneShotCampaign } from '../types';

export const theRoomBeyond: OneShotCampaign = {
  id: 'oneshot-room-beyond',
  type: 'oneshot',
  title: 'The Room Beyond',
  tagline: 'Walk through a 10-foot door. Find a continent.',
  tone: 'exploration',
  themes: ['exploration', 'planar'],
  playerCount: { min: 3, max: 5 },
  level: 5,
  estimatedHours: 3,
  settingSummary:
    'Deep in a well-mapped dungeon, the party opens a door to a room that is 10 feet wide on the outside. Inside, the room stretches to the horizon. Mountains, rivers, forests, a sky with two suns. An entire continent exists inside a dungeon room. The door behind them is still there, a tiny rectangle of torchlight in an infinite landscape.',
  hook: 'The dungeon has been cleared before. Every room is mapped. But the survey team\'s notes say "Room 47: locked, key not found." The party finds the key on a previous floor. The door opens to impossibility.',
  twist: 'The continent is a prison. A god was locked inside this room millennia ago by other gods who could not kill it. The landscape is the god\'s dream made manifest. The god is asleep at the center of the continent. Everything inside, the weather, the creatures, the terrain, is the god dreaming. If it wakes, the room collapses and the god is free.',
  climax: 'The party reaches the center and sees the sleeping god. They must escape without waking it, or find a way to reinforce the prison, or make the terrible choice to wake it and face the consequences.',
  scenes: [
    {
      title: 'Scene 1: Impossible Geometry',
      summary: 'Stepping through and confronting the impossible. An entire world inside a room. The dungeon door behind them shrinks to a pinprick of light.',
      challenge: 'exploration',
      keyEvents: [
        'The threshold: one step from a 10-foot corridor to an open plain under alien skies',
        'Two suns, neither of which casts warmth. The light is bright but the air is cool',
        'The door behind them: visible but miles away from the inside, a glowing rectangle in the sky',
        'Flora and fauna that exist nowhere else: crystalline trees, silent birds, rivers of light',
      ],
    },
    {
      title: 'Scene 2: The Dreaming Land',
      summary: 'Crossing the interior continent. The landscape shifts as the sleeping god dreams. Terrain changes without warning. Weather follows emotion.',
      challenge: 'exploration',
      keyEvents: [
        'The terrain shifts: a forest becomes a desert mid-step, then reverts',
        'Dream echoes: visions of the god\'s memories play out as environmental events',
        'Inhabitants: dream constructs that think they are real and do not know they are inside a room',
        'The center is visible: a mountain that pulses with slow, rhythmic light, like a heartbeat',
      ],
    },
    {
      title: 'Scene 3: The Sleeper',
      summary: 'Reaching the god at the continent\'s center. It sleeps. Everything depends on what the party does next.',
      challenge: 'puzzle',
      keyEvents: [
        'The god: massive, ancient, and sleeping inside the mountain like a heart',
        'The prison wards: carved into the bedrock, weakening over millennia',
        'Reinforcing the prison requires a sacrifice of magical energy from the party',
        'The escape: they must leave quietly, through shifting dreamscape, without disturbing the sleeper',
      ],
    },
  ],
  keyNPCs: [
    { name: 'Survey Captain Rells', role: 'quest giver', personality: 'The dungeon surveyor who locked Room 47\'s entry in the records as "anomalous." She has been trying to get someone to investigate for years. "I opened it once. I saw sky. I closed it and locked it."' },
    { name: 'Orin', role: 'dream construct / guide', personality: 'A shepherd living on the dream continent who does not know he is inside a dungeon room. He has never seen the door. He thinks the world has always been this way. He is kind and helpful and not real.' },
    { name: 'The Sleeper', role: 'the threat', personality: 'A forgotten god imprisoned by its peers. Not evil, but so powerful that its waking would unmake the surrounding region. It dreams of open skies and freedom.' },
  ],
  keyLocations: [
    { name: 'Room 47', description: 'A dungeon door that opens to a continent. 10 feet on the outside. Infinite on the inside.', significance: 'The threshold between the mundane and the impossible.' },
    { name: 'The Dream Continent', description: 'An entire landscape generated by a sleeping god\'s dreams. Two suns, crystalline forests, rivers of light.', significance: 'The exploration space. Every feature is a clue about the god.' },
    { name: 'The Heartmountain', description: 'A mountain at the continent\'s center that pulses with light. The god sleeps inside.', significance: 'The climax location. Where the party decides the god\'s fate.' },
  ],
  dataSystems: ['planarTravel', 'environmentalHazard', 'monsterLore', 'puzzleLock', 'explorationChallenge'],
};
