import type { OneShotCampaign } from '../types';
export const theSunkenTemple: OneShotCampaign = {
  id: 'oneshot-sunken-temple', type: 'oneshot', title: 'The Sunken Temple', tagline: 'The tide goes out once per century. You have 6 hours before it comes back.', tone: 'exploration', themes: ['exploration', 'dungeon_crawl'], playerCount: { min: 3, max: 5 }, level: 7, estimatedHours: 4,
  settingSummary: 'A temple on the coast that is submerged 99% of the time. Once per century, the tide recedes enough to expose the entrance for 6 hours. Inside: ancient treasures, forgotten magic, and the answers to a century-old mystery. The party must explore, loot, and escape before the ocean reclaims the temple — permanently for another 100 years.',
  hook: 'The astronomers predicted it: today, at noon, the Sunken Temple of Nereia surfaces for 6 hours. The last expedition was 100 years ago. They didn\'t come back. The party stands on the cliffs as the sea pulls away, revealing a barnacle-encrusted temple door. The clock starts.',
  twist: 'The last expedition didn\'t die — they\'re still inside, perfectly preserved by the temple\'s magic. They\'ve been frozen in time for 100 years, mid-exploration. The temple freezes anyone inside when the water returns. The party finds the previous explorers and must decide: free them (they\'re from a century ago, everyone they knew is dead) or leave them frozen (technically alive but trapped).',
  climax: 'The water is returning. The party has found the treasure AND the frozen expedition. Freeing the old explorers takes time they might not have. The temple is flooding from the deepest chambers up. A race against rising water with impossible choices about who and what to save.',
  scenes: [
    { title: 'Scene 1: The Emergence', summary: 'The temple surfaces. The party enters. A 6-hour countdown begins. The first rooms are waterlogged and full of sea creatures that didn\'t expect visitors.', challenge: 'exploration', keyEvents: ['The tide recedes: the temple door is exposed, crusted in barnacles and coral', 'Entry: the first rooms are knee-deep in receding water, sea life stranded', 'The temple: ancient, beautiful, designed for an aquatic civilization', 'First discovery: the previous expedition\'s camp — abandoned mid-meal, 100 years ago'] },
    { title: 'Scene 2: The Depths', summary: 'Deeper exploration. Traps designed to work WITH water (currently drained — they\'re malfunctioning in interesting ways). The frozen expedition found.', challenge: 'exploration', keyEvents: ['Water traps: pressure plates that should be underwater, geysers that fire at wrong angles', 'The treasure vault: open, partially looted by the last expedition, still plenty left', 'The frozen explorers: 5 people, mid-step, expressions of surprise, perfectly preserved', 'A journal: the last explorer\'s entry — "The water is coming back. We\'re not going to make—"'] },
    { title: 'Scene 3: The Return', summary: 'The tide returns. Water rises from the deepest chambers. The party must escape with whatever they\'ve found.', challenge: 'combat', keyEvents: ['Water rising: ankle-deep, then knee-deep, then the current starts pulling', 'The choice: free the frozen expedition (takes 10 minutes) or grab treasure and run', 'Aquatic guardians awaken: the temple\'s defenders return with the water', 'The exit: swimming, climbing, and running as the ocean reclaims its temple'] },
  ],
  keyNPCs: [
    { name: 'Captain Sera Brightwind (frozen)', role: 'previous expedition leader', personality: 'Frozen in time, reaching toward the exit. If freed: confused, grateful, and deeply sad — everyone she knew is dead. "It\'s been... 100 years? My daughter... she would be..."' },
    { name: 'The Temple Guardian', role: 'aquatic defender', personality: 'A water elemental bound to protect the temple. Dormant when dry. Active when wet. The rising tide is its alarm clock.' },
    { name: 'Professor Inkwell', role: 'expedition scholar', personality: 'The academic who organized this trip. Has been studying the temple for 30 years. Brought waterproof notebooks. "We have SIX HOURS. Every minute we spend talking is a minute we\'re not DOCUMENTING."' },
  ],
  keyLocations: [
    { name: 'The Sunken Temple of Nereia', description: 'A temple built by an aquatic civilization, normally submerged. Barnacles, coral, and trapped sea life cover every surface.', significance: 'The entire one-shot takes place here.' },
    { name: 'The Treasure Vault', description: 'A partially looted chamber with ancient artifacts, enchanted coral weapons, and pearl-inlaid armor.', significance: 'Where the loot is.' },
    { name: 'The Frozen Chamber', description: 'A room where time stopped when the water returned. Five explorers, frozen mid-flight, preserved for a century.', significance: 'Where the moral choice is found.' },
  ],
  dataSystems: ['dungeonRoomTemplates', 'trapDisarm', 'encounterWaves', 'cataclysmCountdown', 'treasureGenerator', 'combatNarration'],
};
