import type { FullCampaign } from '../types';

export const monstersInc: FullCampaign = {
  id: 'full-monsters-inc',
  type: 'full',
  title: 'Monsters, Inc.',
  tagline: 'The goblins want dental. The skeletons want calcium supplements. The mimic wants to be seen for who it really is.',
  tone: 'comedic',
  themes: ['comedy', 'political', 'social'],
  playerCount: { min: 3, max: 6 },
  levelRange: { start: 4, end: 9 },
  estimatedSessions: 14,
  settingSummary:
    'The dungeon economy runs on monster labor. Goblins guard corridors for minimum wage. Skeletons work double shifts because they do not need sleep (or so management claims). Mimics are classified as furniture, not employees. Gelatinous cubes clean floors without compensation because "that is just what they do." It has been this way for centuries. Until now. The Dungeon Workers Union (DWU, Local 666) has formed, and every monster in the realm is joining. They want health insurance, hazard pay, weekends off, and the right to not be murdered by adventurers without a formal grievance process. Neither the dungeon bosses nor the adventurers\' guild wants to negotiate. The party has been appointed as neutral mediators.',
  hook: 'The Adventurers\' Guild and the Dungeon Bosses\' Association both receive strike notices on the same day. Every goblin, skeleton, mimic, gelatinous cube, and ooze in the region walks off the job simultaneously. Dungeons go dark. Treasure lies unguarded. Adventurers arrive at empty corridors. The economy grinds to a halt. Both sides demand mediation. The party, having no affiliation with either faction, is dragged into the middle. Their first task: get both sides to the same table without anyone being eaten, stabbed, or dissolved.',
  twist:
    'The dungeons are not natural formations. They are infrastructure - magical engines that convert monster labor into the ambient magic that powers civilization. Healers, teleportation circles, enchanted items, even the sun - it all runs on the arcane energy generated by monsters doing repetitive tasks in enclosed spaces. The monsters walking off the job is not just an economic problem. It is an existential one. The ambient magic is fading. If the strike continues, magic itself dies. But telling the monsters they are literally the batteries of civilization would make negotiations worse, not better.',
  climax:
    'Magic is visibly failing. Healing spells sputter. Lights dim. The dungeon bosses threaten to use force. The adventurers\' guild threatens to clear the dungeons the old-fashioned way. The DWU threatens a permanent strike. The party must broker a deal that acknowledges the monsters\' rights, preserves the magical infrastructure, and somehow satisfies everyone - or pick a side and deal with the consequences. The ideal resolution restructures the system so monsters work by choice, are compensated fairly, and the magic is sustained through cooperation instead of exploitation.',
  acts: [
    {
      title: 'Act 1: The Picket Line',
      summary:
        'The strike begins. The party is recruited as mediators and must get representatives from the DWU, the Dungeon Bosses\' Association, and the Adventurers\' Guild to agree to preliminary talks. This is harder than any dungeon.',
      keyEvents: [
        'The strike begins: goblins walk out mid-combat, skeletons put down their swords',
        'The party is recruited by the Mediation Bureau (a bored government agency that has never handled anything this big)',
        'Meeting the DWU leadership: a goblin shop steward, a skeleton organizer, and a mimic who communicates via written notes',
        'The first negotiation attempt: someone throws a chair. The mimic was the chair. It throws itself. Running gag begins: Chester the mimic keeps accidentally becoming the furniture people try to use at every negotiation.',
      ],
      estimatedSessions: 4,
    },
    {
      title: 'Act 2: Demands and Counter-Demands',
      summary:
        'Formal negotiations begin. Each side has unreasonable demands. The party must find common ground while managing egos, grudges, and a mimic that keeps turning into the negotiation table. Meanwhile, magic starts flickering.',
      keyEvents: [
        'The DWU demands: health insurance, hazard pay, a 40-hour work week, and an end to "kill on sight" policies',
        'The Bosses\' counter: they offer a pizza party. The goblins are insulted. Rightfully.',
        'Magic begins failing: a healing potion works at half strength. A teleportation circle sends someone to the wrong city.',
        'The party discovers the connection between dungeon labor and ambient magic',
      ],
      estimatedSessions: 5,
    },
    {
      title: 'Act 3: The New Deal',
      summary:
        'Everything comes to a head. Magic is dying. Hawks on both sides push for war. The party must use everything they have learned to broker a deal, defend the negotiation from saboteurs, and create a new system that works for everyone.',
      keyEvents: [
        'The Adventurers\' Guild sends a strike-breaking team - the party must stop them without violence',
        'The Dungeon Bosses hire scab monsters who are terrible at their jobs (the traps are embarrassing)',
        'The truth about magic comes out - the DWU is furious about being exploited as batteries',
        'The final deal: the party drafts the Dungeon Workers Accord, restructuring the entire system',
        'Callback: Chester turns into the table the Accord is signed on, and for the first time, nobody sits on him — they acknowledge him as a signatory. He cries. The ink runs.',
      ],
      estimatedSessions: 5,
    },
  ],
  keyNPCs: [
    {
      name: 'Gritza Ironteeth',
      role: 'DWU president / ally',
      personality:
        'A goblin shop steward who taught herself labor law by reading discarded adventurer textbooks. She is sharp, organized, and has the patience of a saint - which she needs, because her members include sentient ooze. "We are not asking for the moon. We are asking for Tuesdays off and dental coverage. My members have TEETH, Gerald. Teeth that get punched regularly."',
      secret: 'She does not actually hate adventurers. Her best friend growing up was a human fighter. She is doing this because it is right.',
    },
    {
      name: 'Gerald Goldsworth III',
      role: 'antagonist / Bosses\' representative',
      personality:
        'A human businessman who inherited a chain of dungeons from his father. Has never entered one. Refers to monster employees as "resources" and genuinely does not understand why they are upset. "They get free housing! The dungeon IS their home! Why would they need WEEKENDS?"',
    },
    {
      name: 'Guildmaster Petra Shieldborn',
      role: 'antagonist / Adventurers\' Guild',
      personality:
        'Head of the Adventurers\' Guild. A retired fighter who sees monsters as enemies, period. The concept of monster rights makes her brain short-circuit. She is not evil - she just cannot update her worldview. "You want me to negotiate with the things I spent thirty years KILLING?"',
    },
    {
      name: 'Chester',
      role: 'comic relief / DWU representative',
      personality:
        'A mimic who serves as the DWU\'s public relations officer. Communicates by turning into signs with words on them. Cannot help reflexively biting people who sit on him. He is trying very hard. "I AM NOT A CHAIR. I AM A COMMUNICATIONS PROFESSIONAL."',
    },
  ],
  keyLocations: [
    {
      name: 'The Neutral Ground Tavern',
      description: 'A tavern at the geographic center between the nearest dungeon and the nearest town. Declared neutral territory for negotiations. The bartender is a retired gelatinous cube.',
      significance: 'The primary negotiation venue.',
    },
    {
      name: 'Dungeon 47 (The Strike Site)',
      description: 'A mid-tier dungeon that went dark when the workers walked out. Traps are off. Corridors are empty. Treasure sits unguarded. It is eerie.',
      significance: 'The most visible symbol of the strike and the site of the scab monster fiasco.',
    },
    {
      name: 'The Arcane Engine Room',
      description: 'Deep beneath every dungeon, a hidden chamber where monster labor is converted into ambient magic. The party discovers this. It changes everything.',
      significance: 'The revelation that raises the stakes from economic to existential.',
    },
  ],
  dataSystems: [
    'socialEncounter',
    'diplomaticNegotiation',
    'factionReputation',
    'npcRelationWeb',
    'plotTwistEngine',
    'villainMonologue',
    'combatNarration',
    'politicalEvent',
  ],
};
